POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsMUBtYWlsLmNvbSIsImV4cCI6MTczNzUyNTQ1NywidXNlcklkIjoxfQ.xH3-TiPLbK7FkqVR_BQvd4sY1QuCqGifed3qGc_Pw6Q